# Generated by Django 5.2.6 on 2025-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default="Test ACC", max_length=100),
            preserve_default=False,
        ),
    ]
