# Generated by Django 5.2.6 on 2025-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("incomplete", "incomplete"), ("completed", "completed")],
                default="incomplete",
                max_length=10,
            ),
        ),
    ]
